### ISSUE TITLE
Missing textures and command

### ISSUE THREAD

**Issue by DaBigEgg** [pilot22/museum-robbery#3]
![image](https://user-images.githubusercontent.com/79529277/111910111-f4df6100-8a57-11eb-8b9f-b0d09441cf0a.png)

Hi, the laser and reseller are showing as errors as well as the computer not working! What should I do?

**Comment by pilot22** [comment]
Hello, i'm sorry to hear that. Have you installed the workshop addon ([link](https://steamcommunity.com/sharedfiles/filedetails/?id=1863354376)) on your server's workshop collection ?

**Comment by DaBigEgg** [comment]
Yes

**Comment by pilot22** [comment]
Honestly i dont know 🤔 I will check that when i will have the time

**Comment by pilot22** [comment]
@DaBigEgg Updated, retest the addon please

**Comment by DaBigEgg** [comment]
okay

**Comment by DaBigEgg** [comment]
It works! Thanks!
