### ISSUE TITLE
Make Permanent

### ISSUE THREAD

**Issue by LucaTanks** [pilot22/museum-robbery#4]
Hi, we want to make a museum a permanent POI where paintings automatically restore after 2 minutes and there aren't offers for paintings. Basically, so it is just a new raidable place with advanced security

**Comment by pilot22** [comment]
Hello, I’m sorry, I’m not updating the addon anymore, this repo was an project archive that has been released publicly for being updated with PRs by others devs like what @BullyHunter32 done for the loader.

**Comment by pilot22** [comment]
Whatever, if you have any skills of development, feel free to start the work 😎

**Comment by DaBigEgg** [comment]
I dont have any xD. Sorry, thought you were still developing.
